import Image from 'next/image'
import Header from '@/components/Layout/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Layout/Footer'
import Sidebar from '@/components/Layout/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Dashboard() {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Header />
    <Sidebar />
    {/* {children} */}
    <Footer />
    </body>
  </html>
  )
}
